version: "3.9"  
services:
  webminer:
    container_name: webminer
    restart: unless-stopped
    build:
      context: .
      dockerfile: MinerDockerfile
    volumes:
      - ./webcash.log:/var/opt/webcash/webminer/webcash.log